export default
  [
    {
      "mname": "Nick Stojanovich",
      "title": "Product Manager",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_6.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_1.jpg",
    },
    {
      "mname": "Sina Jamshidi",
      "title": "Director of Engineer",
      "status": "inactive",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_1.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_2.jpg",
    },
    {
      "mname": "Saloni Pal",
      "title": "UX Designer",
      "status": "offline",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_2.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_3.jpg",
    },
    {
      "mname": "Robyn Kwon",
      "title": "HR Manager",
      "status": "offline",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_15.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_4.jpg",
    },
    {
      "mname": "Will Smith",
      "title": "Senior Account Manager",
      "status": "away",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_4.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_5.jpg",
    },
    {
      "mname": "Yann Bachelot",
      "title": "Senior Developer",
      "status": "offline",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_5.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_6.jpg",
    },
    {
      "mname": "Matthew Estes",
      "title": "Program Manager",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_7.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_1.jpg",
    },
    {
      "mname": "Divya Deep Dalotra",
      "title": "Senior Android Developer",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_8.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_2.jpg",
    },
    {
      "mname": "Frank Wang",
      "title": "Senior IT Consultant",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_9.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_3.jpg",
    },
    {
      "mname": "Michael Hopper",
      "title": "Product Designer",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_10.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_4.jpg",
    },
    {
      "mname": "Vincent Baier",
      "title": "Principal Engineer",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_11.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_5.jpg",
    },
    {
      "mname": "Daniel Rahman",
      "title": "Data Scientist",
      "status": "active",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_12.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_6.jpg",
    },
    {
      "mname": "Matthew Waters",
      "title": "Full Stack Developer",
      "status": "offline",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_14.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_2.jpg",
    },
    {
      "mname": "Sabe Mpofu",
      "title": "Frontend Developer",
      "status": "offline",
      "thumbnail": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_small_16.jpg",
      "detailImageUrl": "https://s3.ca-central-1.amazonaws.com/alexluckyq.scriptbucket/images/avatars_full_body_1.jpg",
    },
  ]